services:
  db_to_do:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data_to_do:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  back_end_to_do:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - 5002:5000
    depends_on:
      db_to_do:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://root:root@db_to_do:27017/
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
  

volumes:
  mongo_data_to_do:
    driver: local